/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SaleTransaction {
    customerType: CustomerType;
    transactionDate: bigint;
    totalAmountPees: bigint;
    products: Array<SaleItem>;
}
export interface Product {
    sku: string;
    retailPricePees: bigint;
    quantityInStock: bigint;
    name: string;
    description: string;
    wholesalePricePees: bigint;
    category: string;
}
export interface SaleItem {
    sku: string;
    quantity: bigint;
    priceInPees: bigint;
}
export enum CustomerType {
    retail = "retail",
    wholesale = "wholesale"
}
export interface backendInterface {
    addProduct(product: Product): Promise<void>;
    deleteProduct(sku: string): Promise<void>;
    editProduct(sku: string, updatedProduct: Product): Promise<void>;
    getAllProducts(): Promise<Array<Product>>;
    getProduct(sku: string): Promise<Product>;
    getSales(): Promise<Array<SaleTransaction>>;
    recordSale(customerType: CustomerType, items: Array<SaleItem>): Promise<void>;
}
import type { CustomerType as _CustomerType, SaleItem as _SaleItem, SaleTransaction as _SaleTransaction } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async editProduct(arg0: string, arg1: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editProduct(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editProduct(arg0, arg1);
            return result;
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return result;
        }
    }
    async getProduct(arg0: string): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return result;
        }
    }
    async getSales(): Promise<Array<SaleTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSales();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSales();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordSale(arg0: CustomerType, arg1: Array<SaleItem>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordSale(to_candid_CustomerType_n6(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordSale(to_candid_CustomerType_n6(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
}
function from_candid_CustomerType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomerType): CustomerType {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_SaleTransaction_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SaleTransaction): SaleTransaction {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerType: _CustomerType;
    transactionDate: bigint;
    totalAmountPees: bigint;
    products: Array<_SaleItem>;
}): {
    customerType: CustomerType;
    transactionDate: bigint;
    totalAmountPees: bigint;
    products: Array<SaleItem>;
} {
    return {
        customerType: from_candid_CustomerType_n4(_uploadFile, _downloadFile, value.customerType),
        transactionDate: value.transactionDate,
        totalAmountPees: value.totalAmountPees,
        products: value.products
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    retail: null;
} | {
    wholesale: null;
}): CustomerType {
    return "retail" in value ? CustomerType.retail : "wholesale" in value ? CustomerType.wholesale : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SaleTransaction>): Array<SaleTransaction> {
    return value.map((x)=>from_candid_SaleTransaction_n2(_uploadFile, _downloadFile, x));
}
function to_candid_CustomerType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CustomerType): _CustomerType {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CustomerType): {
    retail: null;
} | {
    wholesale: null;
} {
    return value == CustomerType.retail ? {
        retail: null
    } : value == CustomerType.wholesale ? {
        wholesale: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
