/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'sku' : IDL.Text,
  'retailPricePees' : IDL.Nat,
  'quantityInStock' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'wholesalePricePees' : IDL.Nat,
  'category' : IDL.Text,
});
export const CustomerType = IDL.Variant({
  'retail' : IDL.Null,
  'wholesale' : IDL.Null,
});
export const SaleItem = IDL.Record({
  'sku' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInPees' : IDL.Nat,
});
export const SaleTransaction = IDL.Record({
  'customerType' : CustomerType,
  'transactionDate' : IDL.Nat64,
  'totalAmountPees' : IDL.Nat,
  'products' : IDL.Vec(SaleItem),
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func([Product], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'editProduct' : IDL.Func([IDL.Text, Product], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
  'getSales' : IDL.Func([], [IDL.Vec(SaleTransaction)], ['query']),
  'recordSale' : IDL.Func([CustomerType, IDL.Vec(SaleItem)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'sku' : IDL.Text,
    'retailPricePees' : IDL.Nat,
    'quantityInStock' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'wholesalePricePees' : IDL.Nat,
    'category' : IDL.Text,
  });
  const CustomerType = IDL.Variant({
    'retail' : IDL.Null,
    'wholesale' : IDL.Null,
  });
  const SaleItem = IDL.Record({
    'sku' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInPees' : IDL.Nat,
  });
  const SaleTransaction = IDL.Record({
    'customerType' : CustomerType,
    'transactionDate' : IDL.Nat64,
    'totalAmountPees' : IDL.Nat,
    'products' : IDL.Vec(SaleItem),
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func([Product], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'editProduct' : IDL.Func([IDL.Text, Product], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
    'getSales' : IDL.Func([], [IDL.Vec(SaleTransaction)], ['query']),
    'recordSale' : IDL.Func([CustomerType, IDL.Vec(SaleItem)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };