/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CustomerType = { 'retail' : null } |
  { 'wholesale' : null };
export interface Product {
  'sku' : string,
  'retailPricePees' : bigint,
  'quantityInStock' : bigint,
  'name' : string,
  'description' : string,
  'wholesalePricePees' : bigint,
  'category' : string,
}
export interface SaleItem {
  'sku' : string,
  'quantity' : bigint,
  'priceInPees' : bigint,
}
export interface SaleTransaction {
  'customerType' : CustomerType,
  'transactionDate' : bigint,
  'totalAmountPees' : bigint,
  'products' : Array<SaleItem>,
}
export interface _SERVICE {
  'addProduct' : ActorMethod<[Product], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'editProduct' : ActorMethod<[string, Product], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getProduct' : ActorMethod<[string], Product>,
  'getSales' : ActorMethod<[], Array<SaleTransaction>>,
  'recordSale' : ActorMethod<[CustomerType, Array<SaleItem>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];